# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    test:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            - name: Request translate endpoint
              run: curl -X GET 'https://api.automizely.com/loyalty/whoami'

            - name: Send message to slack channel
              id: slack
              uses: slackapi/slack-github-action@v1.18.0
              with:
                # This data can be any valid JSON from a previous step in the GitHub Action
                payload: |
                  {
                    "status": "${{ job.status }}"
                  }
              env:
                  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

